openapi: 3.1.0
info:
  description: "A FastAPI server for the KnowLang project, providing endpoints for\
    \ all KnowLang features."
  title: KnowLang API
  version: 1.0.0
servers:
- url: /
paths:
  /api/v1/chat/stream:
    get:
      description: Streaming chat endpoint that uses server-sent events (SSE)
      operationId: stream_chat_api_v1_chat_stream_get
      parameters:
      - explode: true
        in: query
        name: query
        required: true
        schema:
          title: Query
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Stream Chat
      tags:
      - chat
  /api/v1/health:
    get:
      operationId: ping_api_v1_health_get
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Ping
      tags:
      - health
  /api/v1/parse:
    post:
      operationId: parse_command_endpoint_api_v1_parse_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParseCommandArgs'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Parse Command Endpoint
      tags:
      - parse
components:
  schemas:
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
      title: HTTPValidationError
    ParseCommandArgs:
      example:
        output: table
        path: path
        extra_fields:
          key: ""
        config: config
        command: parse
        verbose: false
      properties:
        path:
          title: Path
          type: string
        output:
          default: table
          enum:
          - table
          - json
          title: Output
          type: string
        command:
          default: parse
          enum:
          - parse
          title: Command
          type: string
        extra_fields:
          additionalProperties: {}
          nullable: true
        verbose:
          default: false
          title: Verbose
          type: boolean
        config:
          format: path
          nullable: true
          type: string
      required:
      - path
      title: ParseCommandArgs
    ValidationError:
      example:
        msg: msg
        loc:
        - ValidationError_loc_inner
        - ValidationError_loc_inner
        type: type
      properties:
        loc:
          items:
            $ref: '#/components/schemas/ValidationError_loc_inner'
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
    SearchResult:
      description: Standardized search result across vector stores
      properties:
        document:
          title: Document
          type: string
        metadata:
          additionalProperties: {}
          title: Metadata
        score:
          title: Score
          type: number
      required:
      - document
      - metadata
      - score
      title: SearchResult
    ChatStatus:
      description: Enum for tracking chat progress status
      enum:
      - starting
      - polishing
      - retrieving
      - answering
      - complete
      - error
      title: ChatStatus
      type: string
    StreamingChatResult:
      description: Extended chat result with streaming information
      properties:
        answer:
          title: Answer
          type: string
        retrieved_context:
          items:
            $ref: '#/components/schemas/SearchResult'
          nullable: true
          type: array
        status:
          $ref: '#/components/schemas/ChatStatus'
        progress_message:
          title: Progress Message
          type: string
      required:
      - answer
      - progress_message
      - status
      title: StreamingChatResult
      $defs:
        ChatStatus:
          description: Enum for tracking chat progress status
          enum:
          - starting
          - polishing
          - retrieving
          - answering
          - complete
          - error
          title: ChatStatus
          type: string
        SearchResult:
          description: Standardized search result across vector stores
          properties:
            document:
              title: Document
              type: string
            metadata:
              additionalProperties: true
              title: Metadata
              type: object
            score:
              title: Score
              type: number
          required:
          - document
          - metadata
          - score
          title: SearchResult
          type: object
    ServerSentChatEvent:
      properties:
        event:
          $ref: '#/components/schemas/ChatStatus'
        data:
          $ref: '#/components/schemas/StreamingChatResult'
      required:
      - data
      - event
      title: ServerSentChatEvent
      $defs:
        ChatStatus:
          description: Enum for tracking chat progress status
          enum:
          - starting
          - polishing
          - retrieving
          - answering
          - complete
          - error
          title: ChatStatus
          type: string
        SearchResult:
          description: Standardized search result across vector stores
          properties:
            document:
              title: Document
              type: string
            metadata:
              additionalProperties: true
              title: Metadata
              type: object
            score:
              title: Score
              type: number
          required:
          - document
          - metadata
          - score
          title: SearchResult
          type: object
        StreamingChatResult:
          description: Extended chat result with streaming information
          properties:
            answer:
              title: Answer
              type: string
            retrieved_context:
              anyOf:
              - items:
                  $ref: '#/components/schemas/SearchResult'
                type: array
              - type: "null"
              title: Retrieved Context
            status:
              $ref: '#/components/schemas/ChatStatus'
            progress_message:
              title: Progress Message
              type: string
          required:
          - answer
          - status
          - progress_message
          title: StreamingChatResult
          type: object
    ValidationError_loc_inner:
      anyOf:
      - type: string
      - type: integer

