// <auto-generated>
/*
 * KnowLang API
 *
 * A FastAPI server for the KnowLang project, providing endpoints for all KnowLang features.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IParseApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        ParseApiEvents Events { get; }

        /// <summary>
        /// Parse Command Endpoint
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="parseCommandArgs"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IParseCommandEndpointApiV1ParsePostApiResponse"/>&gt;</returns>
        Task<IParseCommandEndpointApiV1ParsePostApiResponse> ParseCommandEndpointApiV1ParsePostAsync(ParseCommandArgs parseCommandArgs, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Parse Command Endpoint
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="parseCommandArgs"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IParseCommandEndpointApiV1ParsePostApiResponse"/>&gt;</returns>
        Task<IParseCommandEndpointApiV1ParsePostApiResponse> ParseCommandEndpointApiV1ParsePostOrDefaultAsync(ParseCommandArgs parseCommandArgs, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IParseCommandEndpointApiV1ParsePostApiResponse"/>
    /// </summary>
    public interface IParseCommandEndpointApiV1ParsePostApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Object>, IUnprocessableContent<Org.OpenAPITools.Model.HTTPValidationError>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 422 UnprocessableContent
        /// </summary>
        /// <returns></returns>
        bool IsUnprocessableContent { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class ParseApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs> OnParseCommandEndpointApiV1ParsePost;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs> OnErrorParseCommandEndpointApiV1ParsePost;

        internal void ExecuteOnParseCommandEndpointApiV1ParsePost(ParseApi.ParseCommandEndpointApiV1ParsePostApiResponse apiResponse)
        {
            OnParseCommandEndpointApiV1ParsePost?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorParseCommandEndpointApiV1ParsePost(Exception exception)
        {
            OnErrorParseCommandEndpointApiV1ParsePost?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class ParseApi : IParseApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<ParseApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public ParseApiEvents Events { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ParseApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ParseApi(ILogger<ParseApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, ParseApiEvents parseApiEvents)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<ParseApi>();
            HttpClient = httpClient;
            Events = parseApiEvents;
        }

        partial void FormatParseCommandEndpointApiV1ParsePost(ParseCommandArgs parseCommandArgs);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="parseCommandArgs"></param>
        /// <returns></returns>
        private void ValidateParseCommandEndpointApiV1ParsePost(ParseCommandArgs parseCommandArgs)
        {
            if (parseCommandArgs == null)
                throw new ArgumentNullException(nameof(parseCommandArgs));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="parseCommandArgs"></param>
        private void AfterParseCommandEndpointApiV1ParsePostDefaultImplementation(IParseCommandEndpointApiV1ParsePostApiResponse apiResponseLocalVar, ParseCommandArgs parseCommandArgs)
        {
            bool suppressDefaultLog = false;
            AfterParseCommandEndpointApiV1ParsePost(ref suppressDefaultLog, apiResponseLocalVar, parseCommandArgs);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="parseCommandArgs"></param>
        partial void AfterParseCommandEndpointApiV1ParsePost(ref bool suppressDefaultLog, IParseCommandEndpointApiV1ParsePostApiResponse apiResponseLocalVar, ParseCommandArgs parseCommandArgs);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="parseCommandArgs"></param>
        private void OnErrorParseCommandEndpointApiV1ParsePostDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, ParseCommandArgs parseCommandArgs)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorParseCommandEndpointApiV1ParsePost(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, parseCommandArgs);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="parseCommandArgs"></param>
        partial void OnErrorParseCommandEndpointApiV1ParsePost(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, ParseCommandArgs parseCommandArgs);

        /// <summary>
        /// Parse Command Endpoint 
        /// </summary>
        /// <param name="parseCommandArgs"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IParseCommandEndpointApiV1ParsePostApiResponse"/>&gt;</returns>
        public async Task<IParseCommandEndpointApiV1ParsePostApiResponse> ParseCommandEndpointApiV1ParsePostOrDefaultAsync(ParseCommandArgs parseCommandArgs, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ParseCommandEndpointApiV1ParsePostAsync(parseCommandArgs, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Parse Command Endpoint 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="parseCommandArgs"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IParseCommandEndpointApiV1ParsePostApiResponse"/>&gt;</returns>
        public async Task<IParseCommandEndpointApiV1ParsePostApiResponse> ParseCommandEndpointApiV1ParsePostAsync(ParseCommandArgs parseCommandArgs, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateParseCommandEndpointApiV1ParsePost(parseCommandArgs);

                FormatParseCommandEndpointApiV1ParsePost(parseCommandArgs);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v1/parse"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/api/v1/parse");

                    httpRequestMessageLocalVar.Content = (parseCommandArgs as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(parseCommandArgs, _jsonSerializerOptions));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));
                    httpRequestMessageLocalVar.Method = new HttpMethod("POST");

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync().ConfigureAwait(false);

                        ILogger<ParseCommandEndpointApiV1ParsePostApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<ParseCommandEndpointApiV1ParsePostApiResponse>();

                        ParseCommandEndpointApiV1ParsePostApiResponse apiResponseLocalVar = new ParseCommandEndpointApiV1ParsePostApiResponse(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v1/parse", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterParseCommandEndpointApiV1ParsePostDefaultImplementation(apiResponseLocalVar, parseCommandArgs);

                        Events.ExecuteOnParseCommandEndpointApiV1ParsePost(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorParseCommandEndpointApiV1ParsePostDefaultImplementation(e, "/api/v1/parse", uriBuilderLocalVar.Path, parseCommandArgs);
                Events.ExecuteOnErrorParseCommandEndpointApiV1ParsePost(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ParseCommandEndpointApiV1ParsePostApiResponse"/>
        /// </summary>
        public partial class ParseCommandEndpointApiV1ParsePostApiResponse : Org.OpenAPITools.Client.ApiResponse, IParseCommandEndpointApiV1ParsePostApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<ParseCommandEndpointApiV1ParsePostApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="ParseCommandEndpointApiV1ParsePostApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ParseCommandEndpointApiV1ParsePostApiResponse(ILogger<ParseCommandEndpointApiV1ParsePostApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Object Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Object>(RawContent, _jsonSerializerOptions)
                    : default;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk(out Object result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public bool IsUnprocessableContent => 422 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.HTTPValidationError UnprocessableContent()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnprocessableContent
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.HTTPValidationError>(RawContent, _jsonSerializerOptions)
                    : default;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnprocessableContent(out Org.OpenAPITools.Model.HTTPValidationError result)
            {
                result = null;

                try
                {
                    result = UnprocessableContent();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)422);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
