/*
 * KnowLang API
 *
 * A FastAPI server for the KnowLang project, providing endpoints for all KnowLang features.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System.Collections.Generic;
using System.Security.Cryptography;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Extensions;
using Xunit;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Tests the dependency injection.
    /// </summary>
    public class DependencyInjectionTest
    {
        private readonly IHost _hostUsingConfigureWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((context, services, options) =>
            {

            })
            .Build();

        private readonly IHost _hostUsingConfigureWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((context, services, options) =>
            {

                options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
            })
            .Build();

        private readonly IHost _hostUsingAddWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {

                });
            })
            .Build();

        private readonly IHost _hostUsingAddWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {

                    options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
                });
            })
            .Build();

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithAClientTest()
        {
            var chatApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IChatApi>();
            Assert.True(chatApi.HttpClient.BaseAddress != null);

            var healthApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IHealthApi>();
            Assert.True(healthApi.HttpClient.BaseAddress != null);

            var parseApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IParseApi>();
            Assert.True(parseApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithoutAClientTest()
        {
            var chatApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IChatApi>();
            Assert.True(chatApi.HttpClient.BaseAddress != null);

            var healthApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IHealthApi>();
            Assert.True(healthApi.HttpClient.BaseAddress != null);

            var parseApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IParseApi>();
            Assert.True(parseApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithAClientTest()
        {
            var chatApi = _hostUsingAddWithAClient.Services.GetRequiredService<IChatApi>();
            Assert.True(chatApi.HttpClient.BaseAddress != null);
            
            var healthApi = _hostUsingAddWithAClient.Services.GetRequiredService<IHealthApi>();
            Assert.True(healthApi.HttpClient.BaseAddress != null);
            
            var parseApi = _hostUsingAddWithAClient.Services.GetRequiredService<IParseApi>();
            Assert.True(parseApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithoutAClientTest()
        {
            var chatApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IChatApi>();
            Assert.True(chatApi.HttpClient.BaseAddress != null);

            var healthApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IHealthApi>();
            Assert.True(healthApi.HttpClient.BaseAddress != null);

            var parseApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IParseApi>();
            Assert.True(parseApi.HttpClient.BaseAddress != null);
        }
    }
}
