/*
 * KnowLang API
 *
 * A FastAPI server for the KnowLang project, providing endpoints for all KnowLang features.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ChatStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatStatus
        //private ChatStatus instance;

        public ChatStatusTests()
        {
            // TODO uncomment below to create an instance of ChatStatus
            //instance = new ChatStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatStatus
        /// </summary>
        [Fact]
        public void ChatStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatStatus
            //Assert.IsType<ChatStatus>(instance);
        }
    }
}
