/*
 * KnowLang API
 *
 * A FastAPI server for the KnowLang project, providing endpoints for all KnowLang features.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResult
        //private SearchResult instance;

        public SearchResultTests()
        {
            // TODO uncomment below to create an instance of SearchResult
            //instance = new SearchResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResult
        /// </summary>
        [Fact]
        public void SearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchResult
            //Assert.IsType<SearchResult>(instance);
        }

        /// <summary>
        /// Test the property 'Document'
        /// </summary>
        [Fact]
        public void DocumentTest()
        {
            // TODO unit test for the property 'Document'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
    }
}
