/*
 * KnowLang API
 *
 * A FastAPI server for the KnowLang project, providing endpoints for all KnowLang features.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ServerSentChatEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServerSentChatEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServerSentChatEvent
        //private ServerSentChatEvent instance;

        public ServerSentChatEventTests()
        {
            // TODO uncomment below to create an instance of ServerSentChatEvent
            //instance = new ServerSentChatEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServerSentChatEvent
        /// </summary>
        [Fact]
        public void ServerSentChatEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServerSentChatEvent
            //Assert.IsType<ServerSentChatEvent>(instance);
        }

        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
